In [1]:
%pip install tabula-py

Requirement already satisfied: tabula-py in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (2.7.0)
Requirement already satisfied: pandas>=0.25.3 in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from tabula-py) (2.0.1)
Requirement already satisfied: numpy in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from tabula-py) (1.24.3)
Requirement already satisfied: distro in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from tabula-py) (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from pandas>=0.25.3->tabula-py) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from pandas>=0.25.3->tabula-py) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\oneen\onedrive\área de trabalho\ferramentas _one\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import tabula
import pandas as pd
from IPython.core.display import display_html
import re

In [3]:
#Leitura do pdf
lista1_cotacao_03 = tabula.read_pdf(r"C:\Users\oneen\OneDrive\Área de Trabalho\FERRAMENTAS _ONE\cdp19023051109003634960000000.pdf", pages="3")
pagina3_cotacao_02 = lista1_cotacao_03[0]
pagina3_cotacao_02.columns = ['indice01','indice02','indice03','indice04','indice05','indice06','indice07','indice08','indice09','indice10']

#Descrição material - Filtragem de descirção somente da tabela 01
descricao_material3 = pagina3_cotacao_02[pagina3_cotacao_02['indice01'].str.contains('Descrição\r')]
descricao_material3 = descricao_material3['indice01'].str.replace('Descrição\r','')
descricao_material3 = descricao_material3.reset_index(drop=True)


#Preço_Unitário - FIltragem de preço unitário da tabela1
preco_unitario3 = pagina3_cotacao_02[pagina3_cotacao_02['indice04'].str.len() > 0]
preco_unitario3 = pagina3_cotacao_02['indice04'].str.contains('Preço Unitário sem I\r')
preco_unitario3 = pagina3_cotacao_02['indice04'].str.replace('Preço Unitário sem I\r','')
preco_unitario3 = preco_unitario3[preco_unitario3.str.len() > 0]
preco_unitario3 = preco_unitario3[~preco_unitario3.str.contains('Emb.\r1')]
preco_unitario3 = preco_unitario3.reset_index(drop=True)
preco_unitario3 = preco_unitario3.apply(lambda x: str(x).replace(",","."))
preco_unitario3 = preco_unitario3.astype('float64')



#Preço total - fitragem de preço total

preco_total3 = pagina3_cotacao_02[pagina3_cotacao_02['indice05'].str.len() > 0]
preco_total3 = pagina3_cotacao_02['indice05'].str.contains('I Preço Total\r')
preco_total3 = pagina3_cotacao_02['indice05'].str.replace('I Preço Total\r','')
preco_total3 = preco_total3[preco_total3.str.len() > 0]
preco_total3 = preco_total3[~preco_total3.str.contains('Qtde.\r')]
preco_total3 = preco_total3.reset_index(drop=True)
preco_total3 = preco_total3.apply(lambda x: str(x).replace(".",""))
preco_total3 = preco_total3.apply(lambda x: str(x).replace(",","."))
preco_total3 = preco_total3.astype('float64')

#mesclando os dados atrávés de cada indice formando uma tabela

df_mesclar03= descricao_material3.to_frame().merge(preco_unitario3,left_index=True,right_index=True)
df_mesclar03= descricao_material3.to_frame().merge(preco_unitario3,left_index=True,right_index=True)
Tabela_01= df_mesclar03.merge(preco_total3,left_index=True,right_index=True)
Tabela_01['indice02'] = Tabela_01['indice05'] / Tabela_01['indice04']


#display
#display(descricao_material3)
#display(preco_unitario3)
#display(preco_total3)
display(Tabela_01)
#display(cotacao_tabela_01)

                  indice01  indice04  indice05   indice02
0                TRENA 5 M   14.6300    438.90  30.000000
1  ESTILETE PROFISSIONAL 6   11.4675    688.05  60.000000
2    ARCO DE SERRA FIXO 12   20.1500    604.50  30.000000
3      CHAVE COMBINADA 8MM    5.4117    324.70  59.999630
4     CHAVE COMBINADA 10MM    5.5867    335.20  59.999642
5     CHAVE COMBINADA 11MM    5.8133    348.80  60.000344
6     CHAVE COMBINADA 12MM    6.1558    369.35  60.000325
7     CHAVE COMBINADA 13MM    6.5400    392.40  60.000000